### ISSUE TITLE
The circle is contractible

### ISSUE THREAD

**Issue by tomjack** [simhu/cubical#9]
As of 5803350 on the connections branch, the following typechecks:

```
module uhoh where

import prelude

S1 : U
hdata S1 = base | loop @ base ~ base

uhoh : Id (Id S1 base base) loop (comp S1 base base base loop loop)
uhoh = refl (Id S1 base base) loop
```

I think 6c1dbbe is where this becomes possible.

**Comment by coquand** [comment]
Yes the order in
- where (ts',indep) = Map.partition (isIndep k i) ts

is not correct; it should be
- where (index,ts') = Map.partition (isIndep k i) ts

**Comment by mortberg** [comment]
Fixed
